#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.hpp"

#include "XtfTypesTest.hpp"
#include "NmeaUtilsTest.hpp"
#include "SurveySystemTest.hpp"
#include "CoordinateTransformTest.hpp"
#include "DataCleaningTest.hpp"
#include "S7kParserTest.hpp"
#include "XtfParserTest.hpp"
#include "BoresightTest.hpp"
#include "S7kTypesTest.hpp"
#include "StringUtilsTest.hpp"
#include "InterpolationTest.hpp"
#include "RaytracingTest.hpp"
#include "GeoreferencingTest.hpp"
#include "SideScanGeoreferencingTest.hpp"
#include "SidescanPingTest.hpp"
#include "CarisSvpTest.hpp"
#include "SvpStrategyTest.hpp"
#include "TimeUtilsTest.hpp"
#include "KongsbergTypesTest.hpp"
#include "KongsbergParserTest.hpp"
#include "DistanceTest.hpp"
#include "CartesianToGeodeticConversionTest.hpp"
#include "PlaneFitAndResidualsTest.hpp"